### ISSUE TITLE
Create Status Endpoint

### ISSUE THREAD

**Issue by vjkoskela** [groupon/kmond#7]
Add status endpoint as status.json with configurable path to return a JSON object which contains:

 - service name
 - build sha
 - version

For example:

```json
{
name: "kmond",
version: "0.0.21",
sha: "eb77cf6212bb50b3dcbfbbf3c897514e5e90d8fc"
}
```

The response data can be generated on build using the filtered resources in maven with the build number plugin.

**Comment by matthayter** [comment]
Addressed with #12
